apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-bastion
  namespace: cwb-event-demo
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        creationTimestamp: null
        name: windows-bastion
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 60Gi
    - metadata:
        creationTimestamp: null
        name: windows-bastion-installation-cdrom
      spec:
        source:
          http:
            url: 'http://192.168.123.100:81/Windows2019.iso'
        storage:
          resources:
            requests:
              storage: 5Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: windows2k19
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: windows-bastion
        kubevirt.io/size: medium
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 2
              disk:
                bus: sata
              name: rootdisk
            - bootOrder: 1
              cdrom:
                bus: sata
              name: installation-cdrom
            - cdrom:
                bus: sata
              name: windows-drivers-disk
            - cdrom:
                bus: sata
              name: sysprep
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - macAddress: '02:83:e4:00:00:08'
              masquerade: {}
              model: e1000e
              name: default
            - bridge: {}
              macAddress: '02:83:e4:00:00:09'
              model: virtio
              name: nic-plain-mosquito
        features:
          acpi: {}
          apic: {}
          hyperv:
            reenlightenment: {}
            ipi: {}
            synic: {}
            synictimer:
              direct: {}
            spinlocks:
              spinlocks: 8191
            reset: {}
            relaxed: {}
            vpindex: {}
            runtime: {}
            tlbflush: {}
            frequencies: {}
            vapic: {}
        machine:
          type: pc-q35-rhel9.2.0
        resources:
          requests:
            memory: 4Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: cwb-event-demo/flatnetwork
          name: nic-plain-mosquito
      terminationGracePeriodSeconds: 3600
      volumes:
        - dataVolume:
            name: windows-bastion
          name: rootdisk
        - dataVolume:
            name: windows-bastion-installation-cdrom
          name: installation-cdrom
        - containerDisk:
            image: >-
              registry.redhat.io/container-native-virtualization/virtio-win-rhel9@sha256:1226b8b5a1768e9a5d40a3a8d2446200664e266cb41912913e160c0058378aba
          name: windows-drivers-disk
        - name: sysprep
          sysprep:
            configMap:
              name: sysprep-windows-bastion-41ulzf
