apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"httpd-24"}]'
    kubemacpool.io/transaction-timestamp: '2024-03-11T19:10:00.559310562Z'
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.resources.requests.memory",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 536870912
        }, {
          "name": "windows-virtio-bus",
          "path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
          "valid": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
          "rule": "enum",
          "message": "virtio disk bus type has better performance, install virtio drivers in VM and change bus type",
          "values": ["virtio"],
          "justWarning": true
        }, {
          "name": "windows-disk-bus",
          "path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
          "valid": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
          "rule": "enum",
          "message": "disk bus has to be either virtio or sata or scsi",
          "values": ["virtio", "sata", "scsi"]
        }, {
          "name": "windows-cd-bus",
          "path": "jsonpath::.spec.domain.devices.disks[*].cdrom.bus",
          "valid": "jsonpath::.spec.domain.devices.disks[*].cdrom.bus",
          "rule": "enum",
          "message": "cd bus has to be sata",
          "values": ["sata"]
        }
      ]
  resourceVersion: '3147493'
  name: windows-bastion
  namespace: cwb-event-demo
  finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
  labels:
    app: windows-bastion
    vm.kubevirt.io/template: windows2k19-server-medium
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.25.0
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        creationTimestamp: null
        name: windows-bastion
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 60Gi
    - metadata:
        creationTimestamp: null
        name: windows-bastion-installation-cdrom
      spec:
        source:
          http:
            url: 'http://192.168.123.100:81/Windows2019.iso'
        storage:
          resources:
            requests:
              storage: 5Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: windows2k19
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: windows-bastion
        kubevirt.io/size: medium
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 2
              disk:
                bus: sata
              name: rootdisk
            - bootOrder: 1
              cdrom:
                bus: sata
              name: installation-cdrom
            - cdrom:
                bus: sata
              name: windows-drivers-disk
            - cdrom:
                bus: sata
              name: sysprep
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - macAddress: '02:83:e4:00:00:08'
              masquerade: {}
              model: e1000e
              name: default
            - bridge: {}
              macAddress: '02:83:e4:00:00:09'
              model: virtio
              name: nic-plain-mosquito
        features:
          acpi: {}
          apic: {}
          hyperv:
            reenlightenment: {}
            ipi: {}
            synic: {}
            synictimer:
              direct: {}
            spinlocks:
              spinlocks: 8191
            reset: {}
            relaxed: {}
            vpindex: {}
            runtime: {}
            tlbflush: {}
            frequencies: {}
            vapic: {}
        machine:
          type: pc-q35-rhel9.2.0
        resources:
          requests:
            memory: 4Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: cwb-event-demo/flatnetwork
          name: nic-plain-mosquito
      terminationGracePeriodSeconds: 3600
      volumes:
        - dataVolume:
            name: windows-bastion
          name: rootdisk
        - dataVolume:
            name: windows-bastion-installation-cdrom
          name: installation-cdrom
        - containerDisk:
            image: >-
              registry.redhat.io/container-native-virtualization/virtio-win-rhel9@sha256:1226b8b5a1768e9a5d40a3a8d2446200664e266cb41912913e160c0058378aba
          name: windows-drivers-disk
        - name: sysprep
          sysprep:
            configMap:
              name: sysprep-windows-bastion-41ulzf
